services:
  backend:
    image: heladeria-django:1.0
    build:
      context: ./backend/config/django-image
    volumes:
      - ./backend/src/django:/usr/src/app:delegated
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SU_NAME=${DJANGO_SU_NAME}
      - DJANGO_SU_EMAIL=${DJANGO_SU_EMAIL}
      - DJANGO_SU_PASSWORD=${DJANGO_SU_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - red
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data:delegated
    networks:
      - red

networks:
  red:
