# Generated by Django 4.2.30 on 2026-07-24 03:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sabor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='socio',
            new_name='es_socio',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fecha',
            new_name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='gramos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='sabores',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_unidades',
        ),
        migrations.RemoveField(
            model_name='sabor',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='medio_pago',
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='producto',
            name='sabores_disponibles',
            field=models.ManyToManyField(blank=True, help_text='Sabores disponibles para este producto', related_name='productos', to='heladeria.sabor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('POTE 1 KG', 'Pote 1 KG'), ('POTE 1/2 KG', 'Pote 1/2 KG'), ('POTE 1/4 KG', 'Pote 1/4 KG'), ('BALDE', 'Balde'), ('MILKSHAKE', 'Milk Shake'), ('CUCURUCHO', 'Cucurucho'), ('VASO', 'Vaso'), ('POSTRE', 'Postre'), ('BOMBÓN', 'Bombón')], default='POTE 1 KG', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='heladeria.producto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('GERENTE', 'Gerente'), ('CAJERO', 'Cajero'), ('LIMPIADOR', 'Limpiador')], max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='max_sabores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sabor',
            name='categoria',
            field=models.CharField(choices=[('CHOCOLATE', 'Chocolate'), ('DULCE DE LECHE', 'Dulce de Leche'), ('FRUTAL', 'Frutal'), ('CREMA', 'Crema'), ('VEGANO', 'Vegano'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
