# Generated by Django 6.0.3 on 2026-04-14 01:50

import django.core.validators
import heladeria.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_unidades',
            field=models.FloatField(default=0, validators=[heladeria.models.validar_no_negativo]),
        ),
        migrations.AlterField(
            model_name='sabor',
            name='stock_kg',
            field=models.FloatField(default=0, validators=[heladeria.models.validar_no_negativo]),
        ),
    ]
