# Generated by Django 6.0.3 on 2026-03-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='letra',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='letra',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
