# Generated by Django 4.2.30 on 2026-08-03 23:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0004_alter_detalleventa_precio_unitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_venta']},
        ),
        migrations.AddField(
            model_name='producto',
            name='consumo_kg_por_unidad',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Kg de mezcla consumidos por unidad de este producto.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AddField(
            model_name='producto',
            name='gramos',
            field=models.PositiveIntegerField(default=0, help_text='Gramos de helado que contiene este producto.'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Fecha de contratación (puede ser nula si no se conoce)', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sabores_disponibles',
            field=models.ManyToManyField(blank=True, help_text='Sabores disponibles para este producto.', related_name='productos', to='heladeria.sabor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('POTE_1KG', 'Pote 1 KG'), ('POTE_500G', 'Pote 1/2 KG'), ('POTE_250G', 'Pote 1/4 KG'), ('BALDE', 'Balde'), ('MILKSHAKE', 'Milk Shake'), ('CUCURUCHO', 'Cucurucho'), ('VASO', 'Vaso'), ('POSTRE', 'Postre'), ('BOMBON', 'Bombón')], default='POTE_1KG', max_length=50),
        ),
        migrations.AlterField(
            model_name='sabor',
            name='categoria',
            field=models.CharField(choices=[('CHOCOLATE', 'Chocolate'), ('DULCE_DE_LECHE', 'Dulce de Leche'), ('FRUTAL', 'Frutal'), ('CREMA', 'Crema'), ('VEGANO', 'Vegano'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
