# Generated by Django 4.2.30 on 2026-08-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0005_alter_venta_options_producto_consumo_kg_por_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='sabores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'disponible': True}, related_name='detalles_venta', to='heladeria.sabor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sabores_disponibles',
            field=models.ManyToManyField(blank=True, help_text='Sabores disponibles para este producto.', limit_choices_to={'disponible': True}, related_name='productos', to='heladeria.sabor'),
        ),
    ]
