# Generated by Django 4.2.30 on 2026-08-04 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0006_alter_detalleventa_sabores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='consumo_kg_por_unidad',
        ),
    ]
